# Generated by Django 6.0.3 on 2026-04-07 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plans',
            name='features',
            field=models.TextField(),
        ),
    ]
