# Generated by Django 6.0.4 on 2026-05-22 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0002_alter_plans_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='class_images/'),
        ),
        migrations.AlterField(
            model_name='class',
            name='sort_order',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='gym',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='gym_images/'),
        ),
        migrations.AlterField(
            model_name='plans',
            name='sort_order',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='trainer_images/'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='sort_order',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.CreateModel(
            name='CmsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('banner', 'Banner')], default='text', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gym_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cms_items', to='gym.gym')),
            ],
            options={
                'verbose_name': 'CMS Item',
                'verbose_name_plural': 'CMS Items',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('gym_id', 'name'), name='unique_cms_item_per_gym')],
            },
        ),
    ]
